{% set name = "inflect" %}
{% set version = "2.1.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4ded1b2a6fcf0fc0397419c7727f131a93b67b80d899f2973be7758628e12b73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - pip
    - setuptools_scm

  run:
    - python

test:
  imports:
    - inflect

about:
  home: http://pypi.python.org/pypi/inflect
  license_file: COPYING.txt
  license: AGPL 3.0
  license_family: AGPL
  summary: 'Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words'
  dev_url: https://github.com/jazzband/inflect
  doc_url: https://github.com/jazzband/inflect

extra:
  recipe-maintainers:
    - pmlandwehr
