{% set name = "inflect" %}
{% set version = "1.0.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "7d8e075740de6e16fead120af6ddb9b97f6d708573431113674b73b10a258352" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
      - inflect

about:
  home: http://pypi.python.org/pypi/inflect
  license_file: COPYING.txt
  license: AGPL 3.0
  license_family: AGPL
  summary: 'Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words'
  dev_url: https://github.com/pwdyson/inflect.py
  doc_url: https://github.com/pwdyson/inflect.py

extra:
  recipe-maintainers:
    - pmlandwehr
