{% set name = "inflect" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: faf19801c3742ed5a05a8ce388e0d8fe1a07f8d095c82201eb904f5d27ad571f

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-build-isolation  --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=61.2
    - setuptools-scm >=3.4.1
    - toml
    - wheel
  run:
    - python
    - more-itertools >=8.5.0
    - typeguard >=4.0.1
    - typing_extensions  # [py<39]

test:
  imports:
    - inflect
  source_files:
    - pytest.ini
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs inflect -v

about:
  home: https://github.com/jazzband/inflect
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
  description: |
    Correctly generate plurals, ordinals, indefinite articles; convert numbers to words
  dev_url: https://github.com/jazzband/inflect
  doc_url: https://github.com/jazzband/inflect

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
