{% set name = "inflect" %}
{% set version = "3.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee7c9b7c3376d06828b205460afb3c447b5d25dd653171db249a238f3fc2c18a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python

test:
  imports:
    - inflect

about:
  home: https://github.com/jazzband/inflect
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
  dev_url: https://github.com/jazzband/inflect
  doc_url: https://github.com/jazzband/inflect

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
