{% set name = "inflect" %}
{% set version = "4.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bafdc6bcfd83ee1e5874607577f7388cd3492cbdb06fc875979c6398ad41ab0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6

test:
  imports:
    - inflect

about:
  home: https://github.com/jazzband/inflect
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
  dev_url: https://github.com/jazzband/inflect
  doc_url: https://github.com/jazzband/inflect

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
