travis:
  secure:
    BINSTAR_TOKEN: TjT8l1sjeiBGV3BaYOotsdNiJdzgHefys2/NYYKfL2u8S/k/mZM5/HE/7L3IBDiypdVb7KWV7EZ/izdpHPGGkz1NRlFJBrO27ySEaz9lT8mtlxX1B+Iw+Kxyh2vrI/A8fFgeHTTwY5ba41EfS5pu2ctchQuSn8N8wINRzc7ENbQQyRtz51p9P54fWmcnCnSlUgDkf8fgiSpY700FygbRMyeKpXMXQeSFkPtoQRYgg9o4pAnlXwZJTM764NiGOcm/HV7ft1jN69bprVxYMJIahcqXRGqjduIr3PqIPwTQjBB5vWN/khNzpt/Kn1Y6m0zkh0h8F1/xNq68DUTooDbzrP0qJBYe61Pqgz4e44SVuEOFX8fnIpFVJ6ixit6xvteiywzaFt/IBJcrSf8Gqtg0QkAA0ns4YCP1Yf9zA6IynN2bQqRpx08539oiO7CVG4vzucoQ5ur+FuhHpYH8oLUqBoz4bnRz/VdRN/xpWswBmzM849W4DnVN7SSVv2YavHiFK303uPnH55DMsLq6fw/LEZpLrfaXIGP6SdWBddNLR15qpvFLi72j1IBHPcZBPNez4OFrAbUNZCxq4cy5PttZ8/CAZJLM5G3tFJ5aA01sNQOpysrYy/PTYAQTs/FiB5BrzJViSe6nEPaiks6EunqfLHXEjA4iixnP2iVvfZvY/No=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
