travis:
  secure:
    BINSTAR_TOKEN: SFmc6HQDzXw9R4qRyKaIV+R5eVEdgQsWQsKsMtbWOi6+ZvR8EkK/pXbJ5D5vL7VExf/LYwdsfGPhENLE8kBqFlHViXf1UYmcpDijNYZDK97ox7+zVuk+HyVqWQPJ1LGdCu1GBxzc2n8nPoicqS3DIZtkKKzWuPSB4fj/xsVcE7EbVNTj5RaMIBjtgWFoZRIc2QdPkmAKwRjj87WhVgoJLo8FJavx4JPugu1xrTmYQ3CGKwEA1ipcZdw7NK7PcHIIe8eQ8XKgeZWbD6yQe29Dfo82Z/ZsEUUARq3VA3IXPNRp3jvihjoRssuqoQFaDGvk+sRMbfXZV9vdaT8LNOEnM4ry2au2Rs4vIkSFQ+deXwEwy8+OTDmeJpOn3XPRGdfnjaUx3ZOKhOvZaYkA+nyat3SJwpdZi0ntoBtYmQvazuqMOfgZErSBUrrrSPa49k3FubJ8UYPoByIsDYBiM6D93mSmUm2IjCNGV8FotiXS6FANzAsjIpbE5dyRxKXIqnYwswtQQ/HHSGS6JGCPJciXn7q3zjp4VHuu89iro6DzovY113p1k4oim9iFIOh13aPaJd5059Xq5MyKJ/wBsuKcGlDl+LP+ylvcTwn0MpRE+nnzLFo5IKX253DY6Mrl5joZifGll8HKphF1wSIvNuG6iFdiYiyKp3IXI3kyogtjPOs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
